### ISSUE TITLE
How do you specify the Vault?

### ISSUE THREAD

**Issue by huyz** [HenryC-3/vscode-plugin-obsidian-code#1]
can't find any settings.

**Comment by HenryC-3** [comment]
Please check out the latest README

**Comment by huyz** [comment]
I already looked in the usual place for extension settings, but this is all I get:
![screenshot 2022-08-01T082035Z](https://user-images.githubusercontent.com/128394/182105480-755bde69-7960-41c9-b489-56a5f518653a.png)

**Comment by HenryC-3** [comment]
Hi @huyz

Did you enable this extension in some workspaces instead of enabling it globally? .

You can use `@installed obsidian-code` in the extension search box to checkout the plugin status.

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/41246463/182110010-9c4a0fc6-60a0-490b-843c-df558394ffad.png">

**Comment by huyz** [comment]
Oh, I had to click "reload required" for some reason.  And now the setting appeared. But your new version only changed the README right?  So I'm not sure why the setting wasn't appearing for the previous version.

It works now, thanks!
